

GET http://localhost:8080/cars
# the request above returns a json object with all cars information from data
### Get person
GET http://localhost:8080/person


###Single requests

GET http://localhost:8080/cars/634a3883807a38278e2408c9


### Create cars
POST http://localhost:8080/cars HTTP/1.1
content-type: application/json

{
        "carMake": "Ford",
        "carModel": "Mustang"  ,
        "engineSize": "170 cu in (2.8 L)",
        "color": "Blue",
        "year": "1969",
        "price": "24673"
}


###Create person
POST http://localhost:8080/person HTTP/1.1
content-type: application/json

{
        "firstName": "Troy",
        "lastName": "Davidson",
        "email": "coolDude@gmail.com",
        "birthday": "01/01/1970"
}

### PUT cars update
PUT http://localhost:8080/cars/634a3883807a38278e2408c9 HTTP/1.1
content-type: application/json

{
        "carMake": "Ford",
        "carModel": "Bronco II",
        "engineSize": "170 cu in (2.8 L)",
        "color": "Brown",
        "year": "1966",
        "price": "44900"
}

### PUT person update
PUT http://localhost:8080/person/634a3883807a38278e2408c9 HTTP/1.1
content-type: application/json

{

        "firstName": "Harmony",
        "lastName": "Davidson",
        "email": "dad@test.com",
        "birthday": "12/17/1980"


}





###Render PRODUCTION ############################


GET https://webbackend-l5-9.onrender.com/cars
# the request above returns a json object with all cars information from data


###

GET https://webbackend-l5-9.onrender.com/person
#gets all persons in my databas.


### Create cars
POST https://webbackend-l5-9.onrender.com/cars HTTP/1.1
content-type: application/json

{
        "carMake": "Dodge",
        "carModel": "Challenger",
        "engineSize": "170 cu in (2.8 L)",
        "color": "Grey",
        "year": "1969",
        "price": "24673"
}



### PUT cars
PUT https://webbackend-l5-9.onrender.com/cars/6472c0126617b0c591438985 HTTP/1.1
content-type: application/json

{
        "carMake": "Dodge",
        "carModel": "Changer",
        "engineSize": "170 cu in (2.8 L)",
        "color": "Grey",
        "year": "1969",
        "price": "25000"
}
