

GET http://localhost:8080/cars
# the request above returns a json object with all cars information from data
### Get person
GET http://localhost:8080/person


###Single requests

GET http://localhost:8080/Hot-cars/634a3883807a38278e2408c9


### Create cars
POST http://localhost:8080/Hot-cars HTTP/1.1
content-type: application/json

{
        "carMake": "Dodge",
        "carModel": "Challenger",
        "engineSize": "170 cu in (2.8 L)",
        "color": "Grey",
        "year": "1969",
        "price": "24673"
}



### PUT cars
PUT http://localhost:8080/Hot-cars/634b1d65bc63e2844311f703 HTTP/1.1
content-type: application/json

{
        "carMake": "Ford",
        "carModel": "Bronco II",
        "engineSize": "170 cu in (2.8 L)",
        "color": "Maroon",
        "year": "1966",
        "price": "44900"
}
### DELETE car
DELETE http://localhost:8080/Hot-cars/634a3883807a38278e2408c9 HTTP/1.1




###Render PRODUCTION ############################


GET https://cse-341-personal-assignments-troy-d.onrender.com/cars
# the request above returns a json object with all cars information from data


###Single requests

GET https://cse-341-personal-assignments-troy-d.onrender.com/cars/634a3883807a38278e2408c9


### Create cars
POSThttps://cse-341-personal-assignments-troy-d.onrender.com/carss HTTP/1.1
content-type: application/json

{
        "carMake": "Dodge",
        "carModel": "Challenger",
        "engineSize": "170 cu in (2.8 L)",
        "color": "Grey",
        "year": "1969",
        "price": "24673"
}



### PUT cars
PUThttps://cse-341-personal-assignments-troy-d.onrender.com/cars/633b860bf1ca7e3a1f473ae6 HTTP/1.1
content-type: application/json

{
        "carMake": "Dodge",
        "carModel": "Challenger",
        "engineSize": "170 cu in (2.8 L)",
        "color": "Grey",
        "year": "1969",
        "price": "24673"
}
### DELETE cars
DELETEhttps://cse-341-personal-assignments-troy-d.onrender.com/cars/633b844a2ffdf3c327b3dc9c HTTP/1.1
