

GET http://localhost:8080/cars
# the request above returns a json object with all cars information from data
### Get person
GET http://localhost:8080/person


###Single requests

GET http://localhost:8080/cars/634a3883807a38278e2408c9


### Create cars
POST http://localhost:8080/cars HTTP/1.1
content-type: application/json

{
        "carMake": " ",
        "carModel": " ",
        "engineSize": "170 cu in (2.8 L)",
        "color": "Grey",
        "year": "1969",
        "price": "24673"
}


###Create person
POST http://localhost:8080/person HTTP/1.1
content-type: application/json

{
        "firstName": "Dennis",
        "lastName": "Davidson",
        "email": "dad@test.com",
        "birthday": "12/17/1980"
}

### PUT cars
PUT http://localhost:8080/cars/634a3883807a38278e2408c9 HTTP/1.1
content-type: application/json

{
        "carMake": "Ford",
        "carModel": "Bronco II",
        "engineSize": "170 cu in (2.8 L)",
        "color": "Maroon",
        "year": "1966",
        "price": "44900"
}

### PUT person
PUT http://localhost:8080/person/634b1f3d807a38278e2408d7 HTTP/1.1
content-type: application/json

{

        "firstName": "Dennis",
        "lastName": "Davidson",
        "email": "dad@test.com",
        "birthday": "12/17/1980"


}
### DELETE car
DELETE http://localhost:8080/cars/634a3883807a38278e2408c9 HTTP/1.1

#### DELETE person
DELETE http://localhost:8080/person/634b39237b249f67844184ba HTTP/1.1




###Render PRODUCTION ############################


GET https://webbackend-l5-9.onrender.com/cars
# the request above returns a json object with all cars information from data


###

GET https://webbackend-l5-9.onrender.com/person
#gets all persons in my databas.


### Create cars
POST https://webbackend-l5-9.onrender.com/cars HTTP/1.1
content-type: application/json

{
        "carMake": "Dodge",
        "carModel": "Challenger",
        "engineSize": "170 cu in (2.8 L)",
        "color": "Grey",
        "year": "1969",
        "price": "24673"
}



### PUT cars
PUT https://cse-341-personal-assignments-troy-d.onrender.com/cars/633b860bf1ca7e3a1f473ae6 HTTP/1.1
content-type: application/json

{
        "carMake": "Dodge",
        "carModel": "Challenger",
        "engineSize": "170 cu in (2.8 L)",
        "color": "Grey",
        "year": "1969",
        "price": "24673"
}
### DELETE cars
DELETE https://cse-341-personal-assignments-troy-d.onrender.com/cars/633b844a2ffdf3c327b3dc9c HTTP/1.1
